version: '3'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
  client:
    build: ./clientAPI
    ports:
      - "8080:8080"
    restart: on-failure
  port-service:
    build: ./portDomainService
    ports:
      - "9090:9090"
    restart: on-failure
    depends_on:
      - mongodb
